version: "3"
services:
    server:
        container_name: "server"
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
        - "3005:3005"
    pg:
        image: "postgres:12"
        container_name: "postgres"
        ports:
          - "5432:5432"
        volumes:
          - ./pg/db_data:/var/lib/postgresql/data
    client:
        container_name: "client"
        build:
            context: .
            dockerfile: ./client/Dockerfile
        ports:
            - "3000:3000"